language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
  - pypy3

services:
  - redis-server

# command to install dependencies
install:
  - pip install -r requirements.txt
   # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi

# command to run tests
script:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then nosetests --with-coverage ./tests/test_decorator.py ./tests/unit_tests.py; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "2.6" ]; then nosetests --with-coverage ./tests; fi
after_success:
  - coveralls